on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.SUB_MODULE_TOKEN }}
        submodules: true

    - name: Preparation on Windows
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build libraries
      run: |
        cmake -B build_debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build_debug --config Debug
        cmake -B build_release -DCMAKE_BUILD_TYPE=Release
        cmake --build build_release --config Release
        
    - name: Test
      run: |
        pushd build_debug
        ctest -C Debug
        popd
        pushd build_release
        ctest -C Release
        popd
        
    - name: Build plugin
      run: |
        pushd plugins/simple_convolver
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        popd
