on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_TOKEN }}
        submodules: true

    - name: Preparation on Windows
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build libraries
      run: |
        cmake -B build_debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build_debug --config Debug -- -j
        cmake -B build_release -DCMAKE_BUILD_TYPE=Release
        cmake --build build_release --config Release -- -j
        
    - name: Test
      run: |
        pushd build_debug
        ctest -C Debug
        popd
        pushd build_release
        ctest -C Release
        popd
        
    - name: Build plugin
      run: |
        pushd plugins/simple_convolver
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release -- -j
        popd

    - name: Create artifacts archive on UNIX platform
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        ARTIFACT_ROOT=artifact_${{ matrix.os }}
        mkdir ${ARTIFACT_ROOT}
        cp -a plugins/simple_convolver/build/SimpleConvolver_artefacts/Release/ ${ARTIFACT_ROOT}
        tar -czf "${ARTIFACT_ROOT}.tar.gz" ${ARTIFACT_ROOT}
        
    - name: Create artifacts on Windows platform
      if: runner.os == 'Windows'
      run: |
        $ARTIFACT_ROOT = "artifact_${{ matrix.os }}"
        mkdir ${ARTIFACT_ROOT}
        Copy-Item plugins/simple_convolver/build/SimpleConvolver_artefacts/Release/ ${ARTIFACT_ROOT} -Recurse
        tar -czf "${ARTIFACT_ROOT}.tar.gz" ${ARTIFACT_ROOT}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          artifact_${{ matrix.os }}.tar.gz
